# name: user.py
# description: SQLAlchemy ORM model for the users table.

import uuid
from datetime import UTC, datetime

from sqlalchemy import DateTime, String, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class User(Base):
    """
    Represents an application user.

    Attributes:
        id: UUID primary key (generated by PostgreSQL).
        email: Unique email used for authentication.
        username: Display name.
        hashed_password: Bcrypt-hashed password.
        level: English proficiency level (A1–C2).
        is_active: Soft-disable flag without deleting the record.
        created_at: UTC timestamp of account creation.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    username: Mapped[str] = mapped_column(String(100), nullable=False)
    hashed_password: Mapped[str] = mapped_column(String, nullable=False)
    level: Mapped[str] = mapped_column(String(5), default="A1", nullable=False)
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    documents: Mapped[list["Document"]] = relationship(  # noqa: F821
        "Document", back_populates="user", cascade="all, delete-orphan"
    )
    conversations: Mapped[list["Conversation"]] = relationship(  # noqa: F821
        "Conversation", back_populates="user", cascade="all, delete-orphan"
    )
    progress: Mapped[list["UserProgress"]] = relationship(  # noqa: F821
        "UserProgress", back_populates="user", cascade="all, delete-orphan"
    )
    weakness_logs: Mapped[list["UserWeaknessLog"]] = relationship(  # noqa: F821
        "UserWeaknessLog", back_populates="user", cascade="all, delete-orphan"
    )
    strength_logs: Mapped[list["UserStrengthLog"]] = relationship(  # noqa: F821
        "UserStrengthLog", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email} level={self.level}>"
