# name: 4aad0490c74f_add_is_fallback_to_messages.py
# description: Alembic migration to add is_fallback column to messages table.

"""add_is_fallback_to_messages

Revision ID: 4aad0490c74f
Revises: c3d4e5f6a7b8
Create Date: 2026-10-03 09:06:20.483365
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4aad0490c74f'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_fallback')
    # ### end Alembic commands ###
