# name: llm_provider.py
# description: Abstract interface (port) for LLM chat providers.
#              Supports both streaming and non-streaming generation.

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from typing import Union

from app.core.primitives.messages import BaseMessage, messages_to_ollama

# Type alias for legacy or low-level chat message dict
ChatMessage = dict[str, str]  # {"role": "user"|"assistant"|"system", "content": str}
MessageInput = Union[list[BaseMessage], list[ChatMessage]]


def normalize_messages(messages: MessageInput) -> list[dict[str, str]]:
    """
    Normalize messages into list of {"role": str, "content": str} dicts.

    Args:
        messages: Sequence of BaseMessage objects or raw dicts.

    Returns:
        List of role/content dictionaries.
    """
    if not messages:
        return []
    if isinstance(messages[0], BaseMessage):
        return messages_to_ollama(messages)  # type: ignore[arg-type]
    return messages  # type: ignore[return-value]


class ILLMProvider(ABC):
    """
    Port interface for LLM text generation providers.

    Implementations wrap specific providers (Ollama, OpenAI, HuggingFace, Anthropic, etc.)
    and expose a unified async API for both streaming and non-streaming generation.
    """

    @abstractmethod
    async def chat(
        self,
        messages: MessageInput,
        temperature: float = 0.7,
        max_tokens: int = 1024,
    ) -> str:
        """
        Generate a full chat response (non-streaming).

        Args:
            messages: Ordered list of role/content dicts forming the conversation.
            temperature: Sampling temperature (0 = deterministic, 1 = creative).
            max_tokens: Maximum number of tokens to generate.

        Returns:
            The generated assistant message as a plain string.

        Raises:
            LLMError: If the provider is unreachable or returns an error.
        """

    @abstractmethod
    async def stream_chat(
        self,
        messages: MessageInput,
        temperature: float = 0.7,
        max_tokens: int = 1024,
    ) -> AsyncGenerator[str, None]:
        """
        Stream a chat response token by token.

        Suitable for Server-Sent Events (SSE) delivery to clients.

        Args:
            messages: Ordered list of role/content dicts.
            temperature: Sampling temperature.
            max_tokens: Maximum tokens to generate.

        Yields:
            Token strings as they are generated by the LLM.

        Raises:
            LLMError: If the provider is unreachable or stream fails.
        """
